name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com (Chinmay and Sayanee)
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: https://webuildsg.github.io/live/feed.xml
destination: ./_publish
permalink: /:permalink
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: http://localhost:4000
audiourl: https://archive.org/download/webuildsglive
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-200.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
